script/java/gen-plainlike.sh
script/java/gen-treelike.sh
script/java/gen-treelike_without_parent.sh
script/java/gen-aggregatelike.sh
script/java/gen-aggregatelike_meta.sh
script/java/gen-aggregatelike_reverse.sh
script/java/gen-aggregatelike_o2o.sh
script/java/gen-aggregatelike_ref_aggregatelike.sh
script/java/gen-extension-details.sh
script/java/gen-extension-master.sh
script/java/gen-graph.sh
script/java/gen-match.sh
script/java/gen-meta_.sh
script/java/gen-meta_full.sh
script/java/gen-pivot.sh
script/java/gen-simple_.sh
script/java/gen-o2o.sh
script/java/gen-o2m_.sh
script/java/gen-o2mp.sh
script/java/gen-o2mo.sh
script/java/gen-o2ma.sh
script/java/gen-ifelse.sh
script/java/gen-canvas.sh
script/java/gen-match_aggregatelike.sh
